import { Container } from '@/styles/Home'
import Head from 'next/head'
import { useState } from 'react'
import Image from 'next/image'

import gitHubIcon from '../assets/githubIcon.svg'
import iconCloud from '../assets/iconCloud.svg'
import iconVerySun from '../assets/iconVerySun.svg'
import iconRain from '../assets/iconRain.svg'
import iconSnow from '../assets/iconSnow.svg'

import favicon from '../../public/favicon.svg'

import Link from 'next/link'


export default function Home() {

  const [search, setSearch] = useState("");
  const [weather, setWeather] = useState("");
  const [imgWeather, setImgWeather] = useState(null);
  const [catchError, setCatchError] = useState("");

  const api = {
    base: 'https://api.openweathermap.org/data/2.5/',
    key: '82bbc64d950a8d5565939dc9bddf5f0c',
    baseImg: 'https://openweathermap.org/img/wn/'
  }

  const searchPressed = async () => {

    await fetch(`${api.base}weather?q=${search}&units=metric&APPID=${api.key}`)
    .then(res => res.json())
    .then(result => {
      setWeather(result);
    });
    await fetch(`${api.base}weather?q=${search}&units=metric&APPID=${api.key}`)
    .then(response => response.json())
    .then(data => {

        const typeIcon = data.weather[0].main;
        if( typeIcon === 'Clouds') {
          setImgWeather(iconCloud);
        } else if(typeIcon === 'Clear') {
          setImgWeather(iconVerySun);
        } else if (typeIcon === 'Rain') {
          setImgWeather(iconRain);
        } else if (typeIcon === 'Snow') {
          setImgWeather(iconSnow);
        }
    })
    .catch(function(error) {
      console.log('There has been a problem with your fetch operation: ' + error.message);
      window.location.href = "error/error-404";
    });

  }

  const returnWeather = () => {

    if(!weather) {
      return (
      <div>
       <h4>
       Write your city name in the search bar
       </h4>
      </div>
    )
  } else if (weather){
    return (
    <div>
        {imgWeather &&
        <>
          <img src={imgWeather.src} alt="ícone do clima" height={80} width={80}></img>
        </>
        }
        {weather && 
          <>
            <h2>{weather?.name + ","} {weather?.sys?.country}</h2>
            <h3>{Math.round(weather?.main?.temp)}º</h3>
            <h4>{weather?.weather[0]?.description}</h4>
            <h5>Max. temperature: {weather?.main?.temp_max.toFixed() + "º"} <br></br> Min. temperature: {Math.floor(weather?.main?.temp_min )+ "º"}</h5>
          </>
        }
      </div>
    )
  } else if (catchError === ''){
    console.log(weather)
    return (
      <div>
       <h4>
       Write your city name in the search bar
       </h4>
      </div>
    )
  }
}

  return (
    <Container>
      <Head>
        <title>Web Weather</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" src={favicon.svg} />
      </Head>
      
      <div>
        <input
        type='text'
        placeholder='search your city...'
        onChange={(e) => setSearch(e.target.value)}
        >
        </input>
        <button onClick={searchPressed}>
          Search
        </button>
      </div>
      
      {returnWeather()}

      <Link href="https://github.com/mayzinng">
        <Image src={gitHubIcon.src} alt="github: mayzinng" width={50} height={50} >
        </Image>
        <h5>mayzinng</h5>
      </Link>

    </Container>
  )
}