import { Container } from '@/styles/error-styles/errorPage'
import Head from 'next/head'
import Image from 'next/image'

import gitHubIcon from '../../assets/githubIcon.svg'

import favicon from '../../../public/favicon.svg'

import Link from 'next/link'


export default function Home() {

  const goToHome = () => {
    window.location.href = '/'
  }

  return (
    <Container>
      <Head>
        <title>Web Weather | Error</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" src={favicon.svg} />
      </Head>
      
      <div>
        <input
        type='text'
        placeholder='search your city...'
        disabled
        >
        </input>
        <button disabled>
          Search
        </button>
      </div>
      
      <div>
        <h4>
            Make sure you entered the name correctly
        </h4>
        <button onClick={goToHome}>
          Go
        </button>
      </div>

      <Link href="https://github.com/mayzinng">
        <Image src={gitHubIcon.src} alt="github: mayzinng" width={50} height={50} >
        </Image>
        <h5>mayzinng</h5>
      </Link>

    </Container>
  )
}